mygazebo:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  front_right_steering_joint:
    type: position_controllers/JointPositionController
    joint: front_right_steering_joint
